name: Build all

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  Love:
    uses: ./.github/workflows/Love.yml
    secrets: inherit
  pku_manager:
    uses: ./.github/workflows/pku_manager.yml
    secrets: inherit
  amnezia-cli:
    uses: ./.github/workflows/amnezia-cli.yml
    secrets: inherit
  snoopage_client:
    uses: ./.github/workflows/snoopage_client.yml
    secrets: inherit